name: hello
description: "A new Flutter FFI plugin project."
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.0


dev_dependencies:
  ffigen: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
 
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
